---
- hosts: aci
  connection: local
  gather_facts: False

  vars:
    apic_info: &apic_info
      host:           "{{ aci_host }}"
      user:           "{{ aci_user }}"
      password:       "{{ aci_password }}"
      validate_certs: "{{ aci_valid_cert }}" 
      use_ssl:        "{{ aci_use_ssl }}" 

  tasks:
    - name: "1] API Request - 收集 System Fault 概况"
      aci_rest:
        <<: *apic_info
        path:   "/api/node/class/faultSummary.json?query-target-filter=or(eq(faultSummary.severity,\"critical\"),eq(faultSummary.severity,\"major\"))&order-by=faultSummary.severity|desc"
        method: get
      register: faults_system
    
    - name: "2] (OPTIONAL) 把收集的信息导出到 JSON 文件中"
      copy:
        content: "{{ faults_system | to_nice_json}}"
        dest:    "./faults_system.json"

    - name: "3] 增加变量 - 消息标题"
      set_fact:
        add_title: "错误信息报告"

    - name: "4] 把数据转换为 Markdown 格式"
      template: 
        src:  "template/faults_report.j2"
        dest: "faults_report.md"

    - name: "5] 读取要发往 Webex 的消息的文件"
      debug:    msg="{{lookup('file', 'faults_report.md') }}"
      register: faults_report
      no_log:   yes 

    - name: "6] 发送 Webex 消息"
      cisco_spark:
        recipient_type: roomId
        recipient_id:   "{{ roomID }}"
        msg_type:   markdown
        personal_token: "{{ bot_token }}"
        msg:        "{{ faults_report.msg }}"